
[[Task]]
== Clustering

The task suite of Rest api allows to start / stop SymetryML kafka stream application. These application are meant to automatically perform prediction on a Kafka
Topic and then save the prediction results in another Kafka topic. 

There is a maximum number of task that can be run at the same time. This number is controlled by the `sml.task.max` 
SymetryML control parameter. Please consult <<TBD>> for more details on how to set these parameters. The default 
value for this `sml.task.max` parameter is 4.

Please consult the <<symetryml kafka stream>> application.

[width="100%", cols="<20%,<20%,<20%,<40%",options="header",]
|=============================
| Parameter | Required/Optional? | Description
| *cluster_rnd_seed* | Optional | Set the seed of the randomizer
| *cluster_max_iterations* | Optional | Default is *1000*. 
| *cluster_num_centroids* | Optional | Default is *100*.
| *cluster_warmup_period* | Optional | Default is *100*.
|=============================

